CogStack/MedCAT

- medcat/cat.py
For Concept addition in the trainer
> Pass more params to cat.add_name

- medcat/cat.py
Added property to `cat` to access the spacy NLP object
> Update cat.py, added property to access the CAT object's spacy 

- medcat/cat.py
- medcat/cdb.py
Fixed get_entities function in cat.py when arg "only_cui=True".
> fix: get_entities func

- tutorial/data/cdb_advanced.csv
- tutorial/data/cdb_simple.csv
Changed prep csv files for cdb to be compatible with medcatv1
> fix: edit tutorial datasets

- README.md
- requirements.txt
- Install requirements from setup.py instead of requirements.txt (like in #9)
- Fix Windows installation (I tested it in Windows 10)
> Update dependency installation

- medcat/preprocessing/iterators.py
- medcat/utils/make_vocab.py
- Enforce UTF-8 like in #8 
- Improve file path handling using pathlib module (see https://realpython.com/python-pathlib/)
> Fix utf8 issue; improve file path handling

- .github/workflows/main.yml
- README.md
- medcat/__init__.py
- medcat/cat.py
- setup.py
- tests/test_ner.py
[CAT-35] Support Python 3.6 again after spaCy upgrade
> Re-support python 3.6

- tutorial/README.md
Added link to tutorial readme to the completed working with snomed ct tutorial
> Added SNOMED CT tutorial links

- medcat/utils/meta_cat/ml_utils.py
> Fix the memory problem in the evaluation loop of meta_cat

- medcat/linking/vector_context_model.py
- medcat/utils/clinical_note_splitter.py
> Fix warning logs

- medcat/utils/meta_cat/ml_utils.py
Hi @w-is-h , this is a small addition to the evaluation functionality of MetaCAT we're using. It might be useful for others as well.
> Add precision and recall in return eval_model

- medcat/utils/preprocess_snomed.py
Minor edits to medcat/utils/preprocess_snomed.py to accommodate the new release format of SNOMED-CT UK extensions >2021.
> Enable the preprocessing of new SNOMED UK extension release format

- README.md
This PR will cover change post releasing the online form.
> Update readme regarding the online form

- docs/conf.py
- docs/main.md
- docs/requirements.txt
- medcat/cat.py
- medcat/cdb_maker.py
- medcat/config.py
- medcat/meta_cat.py
- fix doc build
- use correct docs/conf
- fix some doc warnings in cat.py etc.
- clean up some documentation
> CU-2n9g6yu: Improve docs

- medcat/cat.py
- medcat/cdb.py
- medcat/meta_cat.py
- medcat/pipe.py
- medcat/preprocessing/tokenizers.py
- medcat/utils/make_vocab.py
- medcat/utils/model_creator.py
- medcat/utils/preprocess_snomed.py
__repr__ for CAT and MetaCAT classes also
> More doc improvements

- medcat/cat.py
Breaking up the previous PR _Remove Elasticsearch dependancy #246_
This is to fix the print stats func to display the project name and document name rather than enumerator
> Print_stats fix

- medcat/cogstack/cogstack_conn.py
Set default value to None in CogstachConn function.
> Bug fix during CogstackConn Authentication 

- CONTRIBUTING.md
A very simplistic contribution guideline
> CU-1yfef9z Added initial and simplistic CONTRIBUTING.md

- medcat/config.py
Keeping the previous type in there just in case
> ontology type is wrong with the very latest model

- README.md
- medcat/__init__.py
- medcat/cat.py
- medcat/cdb.py
- medcat/cdb_maker.py
- medcat/cogstack/cogstack_conn.py
- medcat/config.py
- medcat/datasets/data_collator.py
- medcat/linking/context_based_linker.py
- medcat/linking/vector_context_model.py
- medcat/meta_cat.py
- medcat/ner/transformers_ner.py
- medcat/ner/vocab_based_annotator.py
- medcat/ner/vocab_based_ner.py
- medcat/pipe.py
- medcat/pipeline/pipe_runner.py
- medcat/utils/checkpoint.py
- medcat/utils/data_utils.py
- medcat/utils/helpers.py
- medcat/utils/make_vocab.py
- medcat/utils/meta_cat/ml_utils.py
- medcat/utils/ner/metrics.py
- medcat/utils/repair_cdb.py
- medcat/vocab.py
- tutorial/Part_L_Logging_With_MedCAT.html
- tutorial/Part_L_Logging_With_MedCAT.ipynb
As I understand, some users of MedCAT have raised an issue with logging.
The previous logging behaviour was removed in #242. And for good reason. The library should leave the choice of how, when, and where to log information up to the user.
However, there are a few things we can do to make things easier for those users who wish to use the previous behaviour. And we can provide guidance on how to further customise the behaviour of the loggers within the project.
The above is the main aim of this current PR.
In addition to the above, there were a few side objectives
- Move everything to a logger based output (instead of using `print`)
- Make the logging more consistent (each module has its own logger)
Previously, some of the loggers used within the project were package-level loggers. …
> CU-2vzhd93 Logging improvements

- medcat/config.py
Previously resolved a merge conflict in #264 improperly.
This will fix the issue.
> Fix issue with improper conflict merge in previous logging PR

- README.md
Small update to documentation to add URL to paper where the Dutch negation model is assessed.
> Add URL of paper for Dutch model

- medcat/utils/preprocess_umls.py
Adding preprocessing for UMLS.
This is based on MRCONSO.RRF and MRSTY.RRF.
The layout was based on the SNOMED preprocessing. But quite a bit was left out that wasn't applicable at the moment.
> CU-23v5qgn Add UMLS preprocessing

- README.md
> Update ReadMe.md to show Licence change

- setup.py
Fixes https://github.com/CogStack/MedCAT/issues/288
Signed-off-by: zethson <lukas.heumos@posteo.net>
> Loosen dependency restrictions

- docs/requirements.txt
To see if the docs will build now.
> CU-33g0f3w Pin aiohttp dependency version for docs

- docs/requirements.txt
- setup.py
To see if the docs will build now.
> Read the docs build failures

- medcat/cdb.py
- tests/test_cdb.py
Added a function called "remove_cui" to remove a CUI from all places in the CDB.
This was done in response to discourse question:
https://discourse.cogstack.org/t/removing-a-cdb-concept/176/12
> Added function to remove CUI from cdb

- setup.py
Merging into another branch so I can test the build before doing a PR to master.
> CU-862jr8wkk Pin pydantic dependency to avoid conflicts with v2.0

- medcat/cat.py
- more metadata for annotations from print_stats
> CU-862k77jjj: changes needed for Trainer metrics page

- medcat/cat.py
- medcat/config.py
- medcat/utils/preprocess_snomed.py
- tests/helper.py
- webapp/webapp/demo/templates/train_annotations.html
> v1.9.1 Release PR

- README.md
Added a comment regarding load times of demo link to README.
Sometimes it can take well over a minute to load the page. In fact, I was unable to load it up yesterday. But it seems to be up now.
As I understand, the underlying machine (or perhaps the docker container?) spins up when needed and spins down when inactive.
> 869377m3u: Add comment regarding demo link load times to README

- .github/workflows/main.yml
- medcat/cat.py
- medcat/config.py
- medcat/config_meta_cat.py
- medcat/config_transformers_ner.py
- medcat/ner/transformers_ner.py
- medcat/utils/ner/deid.py
- medcat/utils/ner/model.py
- medcat/utils/preprocess_snomed.py
- tests/utils/ner/test_deid.py
- tests/utils/test_preprocess_snomed.py
Preparing for 1.10.2 patch release.
> v1.10.2 PR

- medcat/cdb.py
In preparation for release, removing deprecated method.
> CU-8695j1be2: Remove deprecated method on CDB

- medcat/utils/regression/results.py
While the numeric report was already consistent, the overall textual one could vary due to string hashing differences from one run to another.
This PR mitigates that and makes consecutive runs (with identical models/options/suite) produce identical output in terms of examples as well.
> CU-8695vu71q: Make report identical run to run in identical cases

- .github/workflows/main.yml
- README.md
- install_requires.txt
- medcat/cat.py
- medcat/config.py
- medcat/config_meta_cat.py
- medcat/config_rel_cat.py
- medcat/config_transformers_ner.py
- medcat/meta_cat.py
- medcat/ner/transformers_ner.py
- medcat/stats/kfold.py
- medcat/utils/regression/checking.py
- medcat/utils/regression/regression_checker.py
- medcat/utils/regression/results.py
- medcat/utils/vocab_utils.py
- medcat/vocab.py
- tests/stats/helpers.py
- tests/stats/test_kfold.py
- tests/stats/test_mctexport.py
- tests/test_vocab.py
- tests/utils/regression/test_checking.py
- tests/utils/regression/test_results.py
- tests/utils/saving/test_serialization.py
- tests/utils/test_vocab_utils.py
This a release PR for BETA release v1.15.0b1.
> Release PR for v1.15.0b1

- medcat/meta_cat.py
- medcat/ner/transformers_ner.py
- medcat/tokenizers/meta_cat_tokenizers.py
- medcat/utils/relation_extraction/models.py
- medcat/utils/relation_extraction/tokenizer.py
- medcat/utils/relation_extraction/utils.py
Some things added/changed in `transformers==4.51.0` on Saturday made our workflow fail due to type checks.
This PR should hopefully fix all those issues.
The issues affected a range of different components:
- MetaCAT
- RelCAT
- Transfomers NER
> CU-8698mqu96 Transformers update (4.51.0) fix

- docs/requirements.txt
Bumping some things to make it work, hopefully.
Need to test out still.
> CU-8698vewzp: Fix docs requirements (hopefully)
