README.md, medcat/prepare_cdb.py, medcat/utils/helpers.py, medcat/utils/make_vocab.py
Hi @w-is-h ,
In this PR I added a few changes that helped me in my own deployment of MedCAT. Perhaps it's something others can benefit from as well:
- Made the spaCy model configurable, based on the env variable.
- Improve how output path name is created. This solves the scenario when the output dir name is missing a trailing `/`.
- Make sure Pandas reads all values in the CDB input file as string. This solves a warning with large CDB files.
- Fix typo in README.
Also, I noticed that when the vocab file is saved, the code crashes if the output directory doesn't exist. It might be helpful to add a check before creating the vocab object to see if the directory exists, or just add a make dir statement such as:
```python
if not os.path.exists(output_dir):
os.mkdir(output_dir)
```
=> Small improvements

medcat/preprocessing/iterators.py, medcat/utils/make_vocab.py
This PR specifies an explicit encoding for reading/writing text with UTF-8. Without these changes, I got a `UnicodeEncodeError` when running `make_vocab.make()`, as my text for training the model was encoded with UTF-8.
This might not be the most elegant fix, but UTF-8 seems like a sensible standard, especially for non-English use cases (my text is in Dutch), and this will at least prevent any silent issues.
There are other lines where the encoding could be specified, but these 2 changes seemed to be the only necessary ones for me. 
P.S. I'm working together with @sandertan; he confirmed that these changes did not break anything on his end.
=> Enforce utf-8 encoding

requirements.txt, setup.py
@w-is-h This fixes the failing test in https://github.com/CogStack/MedCATservice/pull/11.
It was caused by a difference in version of `tokenizers`. In `setup.py` it was set to `~=0.8`, which actually installed `0.9.4`, the latest release. The `0.9.x` release contained the code change that made the test fail. I just learned the hard way that to use the latest version `0.8.x`, it should be set to `~=0.8.0`.
While fixing this, I noticed a difference between the `requirements.txt` and `setup.py` in `tokenizers` version. Assuming `0.8.x` is the intended version, I synced them by just putting a single `.` in `requirements.py`. Also just learned to do that :)
https://stackoverflow.com/a/19081268/4141535
Also note that in https://github.com/CogStack/MedCATservice/blob/master/medcat_service/require …
=> Fix version of tokenizers version

medcat/utils/make_vocab.py
Discussed here: https://github.com/CogStack/MedCAT/discussions/29
In my tiny test set, the size of `vocab.dat` shrunk from 800 MB (table size 100,000,000) to 200 KB (table size 10,000)
=> Make unigram_table_size configurable in add_vectors()

medcat/meta_cat.py, medcat/utils/data_utils.py
`tkns_to_ids()` was already commented out in `MetaCAT.train()`, so I removed it from `MetaCAT.eval()` as well. Since there is no functionality left for this function, I removed it entirely... Are you okay with that @w-is-h or do you intend to repurpose it?
Also, I removed  `lowercase=lowercase` from `prepare_from_json()` in `eval()` to align it with `train()`.
=> Fix eval() in MetaCAT

medcat/cat.py, medcat/meta_cat.py, medcat/preprocessing/tokenizers.py, medcat/utils/ml_utils.py
We were encountering an issue that the presence or absence of a space in front of the first word of a sentence changed the results from MetaCAT. This issue occurred relatively often, because our negation training data mostly consists of short texts, so many sentence don't have a space at the start. In longer, real texts, there are probably a lot less of these sentences, see https://discuss.huggingface.co/t/bpe-tokenizers-and-spaces-before-words/475/2 . 
This was solvable with adding a parameter to the tokenizer:
```python
tokenizer = ByteLevelBPETokenizer(add_prefix_space=True)
```
The previous code didn't allow for adding parameters during loading a previously saved tokenizer, so I changed that. I made it flexible (`**kwargs`) so that other parameters can also easily be set. In the …
=> Tokenizer add prefix space

medcat/utils/cdb_helpers.py
- Changed default behaviour of strip_fqn to match existing docstring and presumed intent
- Switched off na_filter for importing SNOMED-CT tsv to fix edge case bug. "N/A" is a real concept in the ontology and should not be considered a missing value.
- Minor cosmetic change to prevent duplication of work and improve readability.
=> Fixes for converting SNOMED-CT source to csv

medcat/cat.py, medcat/cdb.py, medcat/config.py, medcat/linking/context_based_linker.py, medcat/ner/vocab_based_ner.py, medcat/pipe.py, medcat/pipeline/pipe_runner.py, tests/test_cat.py, tests/test_ner.py, tests/test_pipe.py, tests/test_pipe_runner.py
Enable `cat.mutiprocessing_pipe()` to process docs in either the parallel or the sequential manner.
=> Add pipes to cat_ner and cat_liner

medcat/config.py, medcat/pipe.py, medcat/preprocessing/tokenizers.py, medcat/utils/normalizers.py
#117 
These changes enable processing of diacritics in spell checking and cdb maker. For e.g.: a word such as "hyponatriëmie" used to be processsed into "hyponatri~mie", but will now be handled correctly. We tested this on entity linking and it is working correctly.
Together with @sandertan
=> Add functionality to process diacritics

medcat/config.py, medcat/ner/vocab_based_annotator.py
Hi @w-is-h , we noticed that sometimes clinical text contains tokens in uppercase that are semantically identical to a lowercase name in CDB. For example, CDB contains "taxotere", while text is:
> After TAXOTERE treatment
Our previous implementation `check_upper_case_names` recognized this as mismatch, and terminated NER (`return None`) for that token.
In this PR I:
- Solved the above issue by only terminating NER when the CDB name is in uppercase and the token is lowercase. For example to distinguish the concept `MAP` (C0026045) from the lowercase word `map`.
- Simplified this logic by separating it from the next if-statements
- Did not change the next if-statements except for changing the indention.
- Moved the property for `check_upper_case_names` from `config.general` to `config.ner`. …
=> Improve NER of uppercase tokens

medcat/cat.py, tests/test_cat.py
Hi @w-is-h, these are the changes to solve  https://github.com/CogStack/MedCATservice/issues/20.
While searching for other usages, I noticed an independent section of code which uses similarly formatted data that assumes the `entities: dict()` format but is also compatible with the current MCT format `annotations: list()` (which is similar to format `entities: list()` I'm implementing here):
https://github.com/CogStack/MedCAT/blob/50509877b244a624d04758a37259f17fdac1e92d/medcat/utils/meta_cat/data_utils.py#L41 
It uses a MCT export (https://github.com/CogStack/MedCAT/blob/master/tests/resources/mct_export_for_meta_cat_test.json) which is different from the current MCT master format (https://github.com/CogStack/MedCAT/blob/master/tests/resources/medcat_trainer_export.json):
What's the plan …
=> Change entities in output from dict to list

medcat/cat.py, setup.py, tests/test_cat.py
Merging https://github.com/CogStack/MedCAT/pull/207 from dependbot failed the CI with the error `ValueError: Shape mismatch for blis.gemm: (0, 0), (480, 288)`. See in:
https://github.com/CogStack/MedCAT/runs/5216493035?check_suite_focus=true#step:7:427
It was caused by the transitive `blis` being accidentally upgraded to 0.7.6 and spaCy has confirmed the bug in https://github.com/explosion/spaCy/issues/10334
This PR has temporarily pinned down the version of `blis` to 0.7.5 until spaCy can be upgraded with the fix.
=> Pin down the version of blis

medcat/cat.py
Hi,
We were having trouble with the CUI filters in `config.linking['filters']` disappearing after `cat.train_supervised()` was called.
Presumably this isn't expected behaviour? It has been quite annoying because we would like our filters to persist even after printing stats in supervised training. 
The following code I have made up to reveal the problem.
```
from medcat.cat import CAT
from medcat.cdb import CDB
from medcat.vocab import Vocab
cdb_file = 'your_cdb.dat'
vocab_file = 'your_vocab.dat'
annotated_files = 'our_files.json' # our annotated training data
def train(print_=False):
res = {}
cdb = CDB.load(cdb_file)
res['pre_train_len_cdb'] = len(cdb.config.linking['filters']['cuis'])
vocab = Vocab.load(vocab_file)
cat = CAT(cdb=cdb, config=cdb.config, vocab=vocab) …
```
=> Stopping cat._print_stats() from over writing linking filters. 

medcat/cat.py
- fixed the create_model_pack function to work with saving the model pack at paths starting with ~ by adding `expanduser` from `os.path`. It will leave the path unchanged if either no home directory was found or the path does not start with `~`.
- altough I thought adding `pathlib` (#237) would be beneficial here, I decided to go with `os.path` instead. Reasons being:
1. even with `pathlib` one would have to use `expanduser()`
2. Since the whole project already uses `os.path` I did not want to add a new "dependency" (even though its included in the standard library)
Any comments appreciated ;).
=> fix create_model_pack to work with ~ directory

medcat/config.py, medcat/utils/model_creator.py, tests/model_creator/medcat.txt, tests/test_entity_linking.py
- Adding logging reporting functionality to model creator as discussed in #242 
- Improve naming of config in model creator to align with other parts of MedCAT. The previous naming was confusing.
- Simplify model creator test by using letting model creator return a CAT object. 
- Add some documentation on detailed part-of-speech tag. It took me a while to figure out the definitions.
- Use the new version functionality to add some metadata on the test model.
=> Update model creator

README.md, docs/main.md
- Add reference to model download section at top of readme and readthedocs documentation.
- Restructure `## Models` section in readthedocs to prioritize the new UMLS and SNOMED model download location.
=> Update model download section in documentation

medcat/config.py
The recent config changes introduced validation of data types in the config(s).
However, the data type for `version.meta_cats` was incorrect. This caused failure due to validation when doing `cat._versioning` during creating a model pack.
The value was set to an empty `dict` in the previous config version so it was set to the same value and type in the new version as well.
However, when a value is set to this field, a list of strings is used.
This PR will fix the issue by allowing any type of objects to be set for `version.meta_cats`
=> Fixed issue due to data type validation when creating a model pack.

medcat/config.py
If there was ever an issue with the `setattr` method (the `__setattr__` method fails, i.e due to the _pydantic_ model of an extending class), the logging of this issue would fail due to improper arguments to the logging method.
The previous approach should not crash the entire process (since the people developing the _logging_  library will have caught my mistake). However, it would end up with more information than perhaps is needed. And it is certainly a mistake on my end as well.
PS:
Found this due to a new linter that flagged this and a lot of false-positives elsewhere.
=> Fix issue with logging when setting an attribute fails within MixingConfig

setup.py
The docs builds have been failing due to the incompatible version of `dill` that gets installed (incompatible with `datasets`).
I've gone ahead and pinned `dill` to a version less than 0.3.5 (the requirement from `datasets`) so that 0.3.4 gets installed.
This _should_ fix the issue for the docs.
What I tried to make sure this fixes the issue:
- Run the below on python 3.9.14
- Though readthedocs runs 3.9.13, it should be close enough
- Install `dill==0.3.5.1` (as is installed on readthedocs)
- Run `python ./setup.py install --force` (as is done on readthedocs)
- Experience an error due to the mismatch (similarly to readthedocs)
- Install `dill==0.3.4`
- Run `python ./setup.py install --force`
- Experience **no** errors
=> CU-2uhvm87 Pin dill version to less than 0.3.5 to satisfy datasets requirement

medcat/cat.py, medcat/cdb.py, setup.py, tests/test_cdb.py
This PR handles an edge case where if the train count is empty, then the `np.average()` will return `nan` which will be leaked into the stats dict. After the dict is serialised in JSON, `nan` becomes `NaN` which invalids the output. Either 0.0 or None (null) can work fmpov.
Before: {..."Average training examples per concept": NaN}
After: {..."Average training examples per concept": 0.0}
=> Make stats reporting not have np.nan values on empty train count 

setup.py
trainer and medcat service builds failing due to missing dep. Not sure what was pulling this in transitively before...
=> include joblib dep

tests/archive_tests/test_ner_archive.py, tests/helper.py, tests/medmentions/make_cdb.py, tests/test_ner.py, tests/test_pipe.py
Rosalind is currently down. Some MedCAT tests rely on downloading a `Vocab` from `medcat.rosalind.kcl.ac.uk/media/vocab.dat`. When that is not available (currently returns 503), the tests fail since the `Vocab` is (understandably) unable to be loaded from the web response (the 503).
Because of the above, GHA/CIs keep failing due to the test failures.
What this PR does:
- Unify some of the `Vocab` downloads
- Different tests did that separately using identical (or near identical) code
- Checks if the current `tmp_vocab.dat` has the 503 info
- Which cannot be loaded
- If so, tries fetching again
- If rosalind is unavailable
- Generates a simple `Vocab` to use
- If rosalind is available and the current `Vocab` is the generated simple one
- Downloads the new one
Made sure the tests run and …
=> CU-862hyd5wx Rosalind down

medcat/cat.py, medcat/utils/saving/converter.py, medcat/utils/saving/serializer.py, tests/utils/saving/test_serialization.py
The CDB json formatting had some issues:
- the naming through model pack creation would suggest that the model is saved as JSON while only (part of) the CDB was saved as JSON
- The `addl_info` was not included
This PR fixes the above two issues:
- Change formatting parameter in model pack creation
- Since it only affected CDB, made it `cdb_format` (previously just `format`)
- Add `addl_info` to CDB _json_ format
=> CU-862j0jcdu / CU-862j0jd2n Cdb json

medcat/cat.py, medcat/cdb.py, tests/utils/test_hashing.py
Hashing of model packs has been quite slow. This is, in large part, due to the large amount of data being hashed within the CDB. However, in practice, the CDB may not always change. Thus, rehashing it may be a waste of resources (i.e time).
What this PR does is cache the hash for a CDB in memory and track whether or not the CDB has changed (i.e is _dirty_). If the CDB is not dirty, its previous hash is used (if present / known); only if the CDB is dirty (or the hash was not previously known), is the hash recalculated.
The hash is saved on disk, if known. The user can also specify to calculate the hash when saving the CDB if one isn't known. The hash may not be known if the CDB is saved outside a model pack and no hash was read from disk. When saved within a model pack, the hash is known …
=> CU-39cmvru Faster hashing

medcat/utils/preprocess_snomed.py
Main change has been to the processing of snomed refsets to the required medcat models formats.
=> snomed refset processing update

medcat/cat.py, tests/test_cat.py, tests/test_meta_cat.py
This PR provides the options to switch on/off meta models and additional NER modes during the model pack loading. Before this, users had to prepare and maintain multiple model packs as variants to handle “on” and “off” use cases. After this, only one model pack is needed and the default behaviour is all enclosed models will be loaded.
=> Add options for loading meta models and additional NERs

.github/workflows/main.yml
This tiny PR tries to reduce the false-positive errors ("File already exists") from time to time on pushing to test pypi.
=> Reduce the false positives on pushing to test pypi

medcat/ner/transformers_ner.py, tests/test_meta_cat.py
Currently, `transformer_ner` stops processing as soon as the span of a recognised entity (e.g., a subword) does not match any text tokens so the other remaining entities won’t be inspected or added to the `Doc` object. This PR fixed that.
=> Make transformer_ner continue processing other entities after the first non-matching

setup.py
The recent release 1.7.0 has caused the de-id model to throw the following error:
> AttributeError: 'RobertaTokenizerFast' object has no attribute '_in_target_context_manager'
This PR temporarily pins down the dependency as a stopgap measure until a new base model can be trained with the newer release of transformers.
=> Pin down transformers for the de-identification model

setup.py
The readthedocs builds were failing again.
This time the reason was the pydantic version that was installed was the 2.0 alpha and that wasn't compatible with other dependencies.
Pinned pydantic version to less than 2 - it'll have some breaking changes anyway.
Temporarily changed the target for doc builds to confirm that the fix works.
=> CU-862jr8wkk Pin pydantic dependency to avoid conflicts with v2.0 (#318)

medcat/utils/preprocess_umls.py
UMLS preprocessing script did not previously have a way to generate a parent to children mapping which was present in the SNOMED preprocessing script.
This PR adds a method for that mapping.
PS:
UMLS has circular hierarchies ([source](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2243677/pdf/procamiasymp00002-0096.pdf)). As such, so do these mappings. So if a user needs these not to exist, they'd need to preprocess the map.
This also means that getting all children recursively is not possible from the default mapping.
=> CU-863gntc58 Umlspt2ch

medcat/utils/ner/deid.py, medcat/utils/ner/helpers.py
It's weird that GHA (i.e tests) didn't catch this.
But every time I run the current master branch locally, I get a circular import issue.
E.g:
```
Traceback (most recent call last):
File "/Users/martratas/Documents/CogStack/.MedCAT.nosync/MedCAT_2023_01_05/temp/negaccuracy/load_and_check.py", line 3, in <module>
from medcat.cat import CAT
File "/Users/martratas/Documents/CogStack/.MedCAT.nosync/MedCAT_2023_01_05/venv3.10/lib/python3.10/site-packages/medcat-1.2.9.dev334-py3.10.egg/medcat/cat.py", line 24, in <module>
from medcat.pipe import Pipe
File "/Users/martratas/Documents/CogStack/.MedCAT.nosync/MedCAT_2023_01_05/venv3.10/lib/python3.10/site-packages/medcat-1.2.9.dev334-py3.10.egg/medcat/pipe.py", line 19, in <module>
from medcat.ner.transformers_ner import TransformersNER
File …
```
=> CU-862k1tt90 Fix circular imports by moving raw deid method back to helpers module

medcat/cdb.py, tests/test_cdb.py
This is an attempt to allow subsetting of smaller models as well.
In reference to:
https://discourse.cogstack.org/t/advice-on-medcat-for-a-small-set-of-concepts/216
Best I can tell, the only reason the `CDB.filter_by_cui` method fails upon an empty `cui2snames` is because it excpect all CUIs to have snames filled in as well and the method would thus throw an exception otherwise.
Though if someone knows of other reasons, I'd be happy to hear them.
=> CU-86785yhfk Add method to populate cui2snames with data from cui2names

medcat/utils/preprocess_snomed.py
Add missing self argument for method
Fix for #340
=> Fix issue 340 (snomed preprocessing)

medcat/config.py
More specifically the get method which was not able to return default values for non-existant keys.
This PR will make sure the `__getitem__` method of `FakeDict` will raise a _KeyError_ as would be expected for a _dict_ instead of an _AttributionError_ (which was the case up until now).
This will ensure that the `FakeDict.get` method will catch the correct exception in the `except` clause.
Issue raised here:
https://discourse.cogstack.org/t/attribute-error-for-medcat-trainer/234
=> CU-8692kn0yv Fix issue with fake dict in identifier based config

medcat/cat.py
This is still a WIP.
But I identified an issue.
So it looks like when I made the change in #274 I had misunderstood the reason for the copying of the linking filters and "solved" it in a way that made the local filters not available for the vector context model or context based linker.
So effectively, the per-project filters and the extra CUI filters weren't taken into account at all.
So this PR will fix that.
With that said, there may be other issues in there. So I'd say this is still a WIP.
PS:
If someone wants to try this, they can install `medcat` based on this branch:
```
pip install https://github.com/mart-r/MedCAT/archive/CU-8692mevx8-supervised_train_filter.zip
```
Or to try and add it to an older version you can cherry-pick the change:
```
git remote add mrfork …
```
=> CU-8692mevx8 Fix issue with filters not taking effect in train_supervised method

.github/workflows/main.yml, .github/workflows/production.yml, medcat/config.py
Move from Ubuntu 18.04 (which doesn't run on anything anymore) to Ubuntu 20.04 so GitHub Actions can run (both main and production).
=> Fix issue with GHA targets

medcat/config.py, tests/test_config.py
This is related to #313
While the mentioned PR added an option to convert an existing model, this one makes the change on the fly.
This will allow loading older models with this specific issue without any preconditioning (i.e without the need to manually convert).
The only issue I see is that this automatic change (from empty `dict` to empty `set`) is likely to change the hash of the `Config`, which in turns changes the hash of the `CDB`, which in turn changes the hash of the model pack.
While this may not be an issue in of itself, it could cause some confusion.
=> CU-8692uznvd: Allow empty-dict config.linking.filters.cuis and convert to set in memory

medcat/cat.py
The defaults for `get_entities` and `get_entities_mulit_texts` was `['cui2icd10', 'cui2ontologies', 'cui2snomed']`.
Whereas the defaults for `multiprocessing` and `multiprocessing_pipe` was `[]`.
Synced the defaults for the latter two with the former two.
Left the default `_multiprocessing_batch` for untouched since this is a protected method which shouldn't be called from outside the library. And it's currently called within `multiprocessing` along with the `addl_info` passed to it.
PS:
This does still change default behaviour for those using the affected methods. But it shouldn't be too troublesome since all the existing data will still be there. It simply potentially adds new things to the output.
=> CU-2cdpd4t: Unify default addl_info in different methods.

.github/workflows/main.yml, .github/workflows/production.yml
As a result of running on node12, there's warnings such as:
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
This PR updates GHA versions (checkout and setup-python) to v4.
EDIT:
The reason I wanted to fix this is because I have a feeling that's the reason my GHA for #367 keeps getting cancelled. I've re-ran it 10 times and each time something cancels one or multiple of the actions.
=> CU-86931prq4: GHA runs on node12

medcat/cat.py, tests/test_cat.py
There are multiple methods for multiprocessing.
But it is not always clear why one should prefer one to another.
This PR attempts to fix that by deprecating the old methods and renaming them with a new, more descriptive name. It also adds some documentation regarding their differences to the docstrings.
From my research, here's what the differences of the existing methods are:
What I managed to dig up from code and tutorials:
- `multiprocessing`
- Batching based on the character size
- Does not support Windows (at least implied in tutorial Part 3.2)
- `multiprocessing_pipe`
- Batching based on number of documents
- Does support Windows
- `get_entities_multi_texts`
- Used within `multiprocessing_pipe`
- So should be Windows-safe
- Otherwise, more of a convenience method get get_entities
=> Cu 1yn0v9e duplicate multiprocessing methods

medcat/cat.py, medcat/cdb.py, medcat/preprocessing/cleaners.py, tests/preprocessing/test_cleaners.py, tests/test_cat.py
The `CAT.add_and_train_concept` (by using `CAT.add_concept` internally) is able to add new concepts without registering a preferred name.
From my testing, this most likely has to do with the fact that the name specified is too short or empty. The minimum length of names is controlled by `config.cdb_maker.min_letters_required`. If the one (and only) name tied to a CUI has fewer characters than that (defaults to 2), then the `medcat.preprocessing.cleaners.prepare_name` method will return an empty dict and `CDB.add_concept` method cannot add a preferred name.
What I've done so far is the following:
- Add a few tests for prepare_name
- Mostly to better understand how it works and what it does
- Add a warning in `CDB.add_concept` regarding no preferred name
- Add a warning in …
=> Cu 8692zguyq no preferred name

medcat/cdb.py, medcat/pipe.py, tests/test_cat.py
There can be issues when a model doesn't ship with a working `spacy` model. So far, in those cases, the `Pipe` creation fails.
What this PR does is allow a fallback to the per-requirement installed `en_core_web_md` spacy model if there's an issue loading the spacy model that is shipped with the model pack. The issue could be that the sapcy model wasn't packed with the model or that the spacy model isn't compatible with the currently installed `spacy` version.
Along with using a fallback, the PR also generates a warning for the library user to know that they'd be better off shipping with a working spacy model.
=> CU-8693bpq82 fallback spacy model

medcat/pipe.py, medcat/utils/helpers.py, tests/utils/test_helpers.py
When installing medcat using `pip install medcat`, the default spacy model (`en_core_web_md`) does not get installed.
That is because while it is specified in `requirements.txt` and `requirements-dev.txt`, it would need to be specified in `setup.py`'s `install_requires` in order to be shipped with the dependency.
As such, we're left with two options:
1. Add the dependency to `install_requires`
2. Download the model when falling back to default model and it isn't available
I've chosen the latter option.
To that end, I've added:
- A method to detect whether a specific spacy model is installed
- A method to ensure a specific spacy model is installed
- A few tests for the above
=> CU-8693cv3w0 Fix fallback spacy model existance on pip installs

requirements-dev.txt, requirements.txt, setup.py, tests/resources/ff_core_fake_dr/meta.json, tests/test_ner.py, tests/utils/test_spacy_compatibility.py
There's can be some issues with dependency versions.
This is mostly with respect to `spacy` and `dill`. In essence, we've been depending on higher versions than that defined in `setup.py`.
This is because by default a significantly higher version of `spacy` is installed compared to the low end of the requirement.
And some things saved with `dill>=0.3.6` are not readable with `0.3.4` and `0.3.5`.
However, if one were to upgrade from an older version of `medcat`, if the dependency range allows the current version of a dependency (e.g `spacy` or `dill`), pip will not upgrade it. As such, one might arrive with an incompatible state of dependencies even for models created and/or saved in the same `medcat` version.
The motivation for this change is as follows:
- Some newer models (in my case, …
=> CU-8693kp0gw: Pin more recent versions for major dependencies; Avoid major bumps where applicable

medcat/config_meta_cat.py, medcat/meta_cat.py, tests/test_meta_cat.py
Hello - I opened this PR request to start a discussion about adding a new feature that allows a trained MetaCAT model to run on arbitrary spangroup. This will will allow configuring a MetaCAT model such that it can be pointed at an arbitrary spacy span group and set meta_anns on it.
Currently, it is allowed to run on the two set of `list[spacy.token.Span]`: `doc.ents` or `doc._.ents`.
However, there are use cases where we may store other spans as part of a pipeline under `doc.spans["my_spangroup_name"]` that are distinct from doc.ents in which we want to call predict on the meta cat model.
I don't think it's yet necessary to be able to train on arbitrary spangroups since that would get into changing the input format or extract format from medcat trainer.
One workaround is to either zero …
=> add: metacat can predict on spans in arbitrary spangroups

requirements-dev.txt
Mypy currenlty checks `torch` and fails along with GitHub Actions because of it.
Seems that bumping the mypy version fixes the issue.
This PR:
- Bumps `mypy` version to `>=1.7.0` 
- Allows compatible extensions (`mypy-extensions>=1.0.0`)
- Pins `mypy` max version to current major version (`<2.0.0`)
=> CU-8693ruk7p: Bump mypy version in dev-requirements

requirements-dev.txt
* CU-8693ruk7p: Bump mypy version (along with extensions) in dev-requirements
* CU-8693ruk7p: Pin max major version for mypy
=> CU-8693ruk7p: Bump mypy version in dev-requirements (#396)

medcat/ner/transformers_ner.py
In `medcat==1.9.3` there was a change to the `transformers` dependency range (from `transformers>=4.19.2,<4.22.0` to `transformers>=4.34.0`). That change also removed the comment that the pin was for the DeID model to work.
I've looked into the issue and believe I've got a workaround for it.
The newer versions of transformers (starting rom `4.22.0`) expect the tokenizer to have a specific attribute (`_in_target_context_manager`). However, as we load it off disk, the attribute doesn't exist since the saved version is older.
The change reference:
https://github.com/huggingface/transformers/pull/18325
So what this PR does is add the missing attribute to the tokenizer.
I've tested locally with the DeID model and after this change, it worked just fine.
PS:
This isn't really easy to test …
=> CU-8693t24ed: Add workaround for older DeID models in newer MedCAT

.github/workflows/main.yml, medcat/config_meta_cat.py, tests/utils/ner/test_deid.py
* CU-8693u6b4u: Make sure failed/errored tests fail the main workflow
* CU-8693u6b4u: Attempt to fix deid multiprocessing, at least for GHA
* CU-8693u6b4u: Fix small docstring issue
=> v1.10.1 PR (attempt 2)

medcat/utils/preprocess_snomed.py, tests/utils/test_preprocess_snomed.py
The OPCS4 refset ID in the current version is `1126441000000105` . However, in SNOMED2024 it seems to be `1382401000000109`.
So this PR changes the behaviour of the snomed preprocessor.
It also adds a method to convert the ICD10/OPCS4 mappings to direct mapping.
And adds some tests as well.
=> CU-8693v3tt6 SOMED opcs refset selection

medcat/config.py
The config had imports typing helpers (`Any`, Callable , Dict ,`Optional`, `Union` ) from `pydantic.dataclasses` instead of directly from `typing` .
Most likely an automatic import that I forgot to fix at the time.
Making sure to import from the proper package.
=> CU-8693v6epd: Move typing imports away from pydantic

medcat/cat.py, medcat/config_transformers_ner.py, medcat/ner/transformers_ner.py, medcat/utils/ner/deid.py, medcat/utils/ner/model.py, tests/utils/ner/test_deid.py
Adding functionality for chunking documents that exceed the maximum number of tokens the model can process.
- Used hugging face pipeline functionality to perform chunking with overlap.
- Added an attribute 'chunking_overlap_window' to the NER config to control the size of the overlap window (default value set to 5)
=> CU-8693qx9yp Deid chunking - hugging face pipeline approach

medcat/cat.py, setup.py, tests/test_cat.py
The underlying issue manifested in the following way:
When calling `multiprocessing_batch_char_size` the output would come out completely empty. Nothing logged as to what happened or why.
This is because the machine in question has 128GB of RAM and the default minimum expected RAM is 10%. And the machine happened to have around 6GB of free memory. Which is less than 5% (and less than the minimum required).
The solution for the user is to specify a smaller `min_free_memory` value when calling the method (e.g `0.005` in this case for around 500MB).
So what this PR does:
- Adds logged warning for when this happens along with suggestion for a fix
- Adds and uses new argument `min_free_memory_size` where users can specify a human-readable minimum memory amount
This way, in future cases, we'll …
=> CU-86949yar7: Add logged warning for when multiprocessing fails due to being out of memory

medcat/cat.py, tests/test_cat.py
Add progress bar to `CAT.multiprocessing_batch_char_size`.
If the data is given in something that has a length (i.e `list`, or `tuple`) it will be able to estimate the time left. Otherwise it just shows the time per batch (as per normal).
Also added option to disable the progress bar.
=> CU-86949zjg9 mp progress

medcat/utils/preprocess_snomed.py
This PR will make preprocessing work for the AU release if the folder structure is the same as it is for the UK and international releases:
`SnomedCT_{description}_{release}/Snapshot/Terminology/sct2_{files}.txt`
I.e a file like this exists:
`SnomedCT_Release_AU1000036_20240331T120000Z/Snapshot/Terminology/sct2_Description_Snapshot-en-AU_AU1000036_20240331.txt`
EDIT:
Just to clarify, in the example I've got, the relationship file (`sct2_Relationship_Snapshot_{SNOMED_VER}_{SNOMED_RELEASE}.txt`) does not seem to include the `-AU` part.
=> CU-8694cbcpu: Allow specifying an AU Snomed when preprocessing

medcat/meta_cat.py, medcat/ner/transformers_ner.py
Alternative to #422
Instead of restricting `mypy` version fixes the underlying issue. I.e returns empty generators where applicable.
=> CU-8694dpy1c: Return empty generator upon empty stream

.github/workflows/production.yml
What this PR does:
- During production workflow
- Determines if a release is a pre-release on GitHub
- If a release is a pre-release on GitHub, does not publish on PyPI
PS:
This is rather difficult to test since I cannot do the same in the main workflow because no release or pre-release is involved there.
The rationale:
If we want to do a Clinical Safety Review of a new release before publishing it on PyPI, we can draft a pre-release here on GitHub. Then we can process the review. And after that we can remove the pre-release tag and re-run the action to publish on PyPI.
=> CU-8694fae3r: Avoid publishing PyPI release when doing GH pre-releases

medcat/cdb.py, medcat/config.py, medcat/linking/vector_context_model.py, medcat/utils/config_utils.py, medcat/utils/saving/coding.py, tests/test_cat.py, tests/test_config.py, tests/utils/saving/test_serialization.py, tests/utils/test_config_utils.py
This PR removes `weighted_average_function` from the config and ties it to the `CDB` instead.
The idea is to be able to more simply save and load configs in a simpler json format.
So the PR also makes new saves of the config saved in (mostly) regular json.
There are a few caveats:
- Custom serialisation is used for `set`s and `re.Pattern`s
- And custom decoding as well
- So that means that a simple `json.load` will not create a useful dict to merge into a config
Some further things to note:
- The PR still allows loading old-style `jsonpickle`d configs
- Some things may have been moved around a little for simplicity
- This PR may complicate some things
- There's a backwards compatibility method that already fixes `weighted_average_function` issues
- I.e makes sure they're not `lambda`s
- …
=> CU-8694fk90t (almost) only primitive config

medcat/cat.py, medcat/cdb.py, medcat/meta_cat.py, medcat/utils/decorators.py, medcat/utils/ner/helpers.py, tests/__init__.py, tests/test_cat.py, tests/test_meta_cat.py
We've got a few deprecated methods in MedCAT. But there isn't much documentation as to when they might get removed.
There also isn't anything that would check for the usage of deprecated methods in the codebase.
So what this PR does is improve the situation by:
- Adding deprecation and removal version arguments to the deprecation decorator
- Along with filling in the details for existing methods
- Makes deprecated methods raise an exception during test time
- So that we (hopefully) avoid using them in our test suite and/or codebase
- Fixes uses of deprecated methods in the tests
=> CU-8694n48uw better deprecation

medcat/config.py, medcat/utils/config_utils.py, tests/resources/jsonpickle_config.json, tests/resources/jsonpickle_meta_cat_config.json, tests/resources/jsonpickle_rel_cat_config.json, tests/resources/jsonpickle_tner_config.json, tests/utils/test_config_utils.py
The last PR for (almost) primitive config (#425) had a few issues:
- It didn't correctly identify all old style configs (e.g `ConfigMetaCAT`)
- It didn't correctly apply options loaded from old style configs (even for regular config)
This PR fixes the above.
It also adds tests for old types of config (regular, MetaCAT, TNER, and RelCAT).
For each, it makes sure that they're classified as old style, and that a value changed within them is correctly identified as having been changed / loaded off disk.
=> CU-8694py1jr fix old config load with reg json

medcat/ner/transformers_ner.py
3rd of June when merging 
https://github.com/CogStack/MedCAT/pull/449
We had the following dependencies installed on GHA:
https://gist.github.com/mart-r/fbcaf2efd797a61b610148dc2772ac36
And the actions ran successfully:
https://github.com/CogStack/MedCAT/actions/runs/9347830207/job/25725635617
(the log will be erased at some later date - I think it was 90 days)
On 17th and 18th of June, when trying to merge
https://github.com/CogStack/MedCAT/pull/438
We had the following dependencies installed:
https://gist.github.com/mart-r/0581771a9db05d5b33e6eff4e6f05a60
And the GHA FAILED:
https://github.com/CogStack/MedCAT/actions/runs/9550033321/job/26321052562?pr=438
With failed tests (in case this is not showing)
https://gist.github.com/mart-r/6bbbd7225d0cc52446bf2ab75fa675b0
The differences in …
=> CU-8694vcvz7: Trust remote code when loading transfomers NER dataset

.github/workflows/main.yml, tests/check_deprecations.py
Make sure deprecated methods are removed before next release.
What this PR does:
- Adds a small bit of code that
- Finds all deprecated methods
- Checks if each deprecated method is already supposed to have been removed
- Adds these checks to the main GitHub Actions workflow
- But only runs right before a release, for `master` -> `production` PR
How it determines what's "supposed to be removed":
- It determines the latest release on GitHub within GitHub Actions
- It then increments the minor version (`<major>.<minor>.<patch>`)
- If the `removal_version` argument of a deprecated method is higher than or equal to the upcoming (minor) release, this method is deemed to need removal
Some caveats:
- This relies on the assumption of the next release version being the next minor version
- …
=> CU-8694p8y0k deprecation GHA check

medcat/cat.py, medcat/cdb.py, tests/test_cdb_maker.py
Name removal may be a little confusing. There's a `CDB.remove_names` method, but it seems to require a `Dict[str, Dict]` whereas in reality it only just iterates over the keys of this `dict`.
Realistically, users should probably usually use `CAT.unlink_concept_name` instead.
With that said, what this PR does:
- Protects (prepends with `_`) the `CDB.remove_names` (so now `CDB._remove_names`)
- Keeps a deprecated `CDB.remove_names` method due for removal in medcat v`1.13`
- Add a log message to `CAT.unlink_concept_name` when doing a full-unlink (as per config)
- Makes `CDB._remove_names` accept and use `Iterable[str]` instead of `Dict[str, Dict]`
NOTE:
While looking at some of the tests that used `CDB.remove_names`, I saw that some of the tests (probably more than I actually noted down) are …
=> CU-8694u3yd2 cleanup name removal

medcat/cat.py, medcat/config.py, medcat/utils/usage_monitoring.py, tests/test_cat.py, tests/utils/test_usage_monitoring.py
Add a usage monitor.
What it does is monitor:
- The input text length
- The input preprocessed text length
- The number of output entities
The usage monitor is configured such that it logs on file every time 10 (configurable) inferences are logged (to avoid constant IO). It also logs the rest of the buffer when the user monitor is dereferenced.
This PR also adds the relevant config part (`config.general.usage_monitor`). The usage monitoring can be disabled if needed by changing the config.
=> CU-8694wh3d5 track usage

medcat/utils/saving/envsnapshot.py, tests/utils/saving/test_envsnapshot.py
Add all transitive dependencies to the environmental snapshot.
We added transitive dependencies to MedCAT in v1.12 (#438). However, that only included direct dependencies of MedCAT.
In principle, the compatible versions of transitive dependencies should be handled by the package that defines them. However, these things can change over time and there may be a situation where the requirements ranges previously set no longer work properly. As such, by including all the transitive dependencies (and their versions) in the environmental snapshot could help us recreate an environment where we'd expect a model to work more confidently.
There's a few decisions I made that _could_ very well be open to change:
1. Currently, the transitive dependencies are in a separate part of the json
- I thought …
=> CU-8694vv985 transitive deps

install_requires.txt
`blis==1.0.0` is automatically installed, even though it depends on `numpy>=2.0.0,<3.0.0 ` (which is not compatible).
This shouldn't really happen. `pip` should recognise that`blis==1.0.0` is not compatible.
Regardless, this PR will pin `blis` to less than 1.0.0.
PS:
First GHA will fail (on python 3.8) to demonstrate the failure by default.
=> CU-869588fdc: Comment on blis 1.0.0 (to show GHA failure)

medcat/config_meta_cat.py, medcat/meta_cat.py
Adding more description to the config for metacat and adjusting text to avoid rendering issues
=> Changes to documentation for metacat

medcat/utils/meta_cat/ml_utils.py, medcat/utils/meta_cat/models.py
Fix issues with compute_class_weights JSON serialization and enforce fc2 usage when fc3 is enabled
- Resolved an issue where compute_class_weights returns a NumPy array, causing an error when saving the configuration as JSON (since JSON does not support NumPy arrays). The fix ensures compatibility by converting the NumPy array to a JSON-serializable format.
-  Added a safeguard in the model_architecture_config for meta_cat_config. The current architecture assumes fc3 is only used when fc2 is enabled. If fc2 is set to False and fc3 is True, the model would fail due to a mismatch in hidden layer sizes. The fix automatically enables fc2 if fc3 is set to True, preventing potential errors.
=> Fixing bug for metacat

medcat/utils/versioning.py
Due to some changes (e.g #425), models created in medcat 1.12 are not compatible with lower versions of MedCAT.
However, since I've created the new Snomed 2024-06 (naming based on Snomed release) model with medcat 1.12 and most people are probably not on 1.12 yet, I've made this PR to allow me to still be able to propagate the new model to users of 1.11 or 1.10.
Tested this on the Snomed-2024-06 model I'm working on. And the modified version was working fine on medcat 1.10.2 and 1.11.0.
=> CU-86956duhb: Add method to backport a model pack from 1.12 to previous version

medcat/cat.py
The UsageMonitor PR #458 missed something.
Since the usage monitor is attempting to save to a file that has the hash of the model as part of its name, it is looking for the model's hash upon initialisation. The assumption is that this can easily be found since the CDB carries its hash with it (since #286 / release 1.8.0). However, older models did not have the CDB hash saved. As such, during the creation of the usage monitoring, the CDB hash was calculated.
Now, this PR will change the behaviour and use the hash that's in `config.version.id` instead of recalculating it.
=> Use the loaded model hash for usage monitor instead of recalculating it

medcat/utils/regression/regression_checker.py
Turns out the `%` in the description for an argument broke the argument help (i.e `--help`).
This PR fixes that by escaping the `%`.
<details>
<summary>Longer description of issue</summary>
Turns out `python -m medcat.utils.regression.regression_checker --help`  raises an exception due to a description having `%`  in it, e.g:
```
Traceback (most recent call last):
File "/Users/martratas/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/martratas/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/Users/martratas/Documents/CogStack/.MedCAT.nosync/MedCAT/medcat/utils/regression/regression_checker.py", line 172, in <module>
args = parser.parse_args() …
```
=> CU-8695jwnjk: Fix description of an argument for --help to work in CLI

medcat/meta_cat.py, medcat/utils/meta_cat/data_utils.py, medcat/utils/meta_cat/ml_utils.py, medcat/utils/meta_cat/models.py
2-phase learning for MetaCAT utilises `data_undersampled`. 
Fixed a bug in the `eval` function, which was incorrectly using the `data_undersampled` instead of the `full_data`
=> Pushing bug fix for metacat

docs/main.md
When we moved our links (e.g in tutorials https://github.com/CogStack/MedCATtutorials/pull/12 ) from rosalind to S3 the ones in the docs were missed.
This PR fixes them.
PS:
There's still a few `medcat.rosalind.kcl.ac.uk`-related links in `README.md` and `docs/main.md`. They are either for the demo link or the model download referral. They all still work. That's because the demo app is still up on that domain.
=> CU-8695q21f6: Replace rosalind links with S3 ones in docs

medcat/ner/vocab_based_ner.py
The underlying issue presented in models sometimes being unable to recognise a concept where the same model would recognise an incorrectly typed name in the exact same context.
<details>
<summary>A few more details as to how I came onto this issue</summary>
Tested with a few different models:
- [1] The 2022/2023 GSTT/KCH trained model
- [2] The AU model (where I first saw the issue)
- [3] The 2024-06 GSTT-trained model
I ran with 2 separate "documents":
```
Patient was diagnosed with diabetes based on previous findings
```
And
```
Patient was diagnosed with diabetis based on previous findings
```
(Note the typo of diabetis instead of diabetes  in the 2nd).
Some models ([1] and [3]) were able to correctly identify the 2nd (i.e typo'd) version, but not the 1st (i.e correctly typed version). …
=> CU-8695m5q4x: Fix issues detecting 1-token concepts

medcat/cat.py, tests/test_cat.py, tests/utils/test_usage_monitoring.py
Previously usage monitoring wouldn't work for multiprocessing.
The issue was 2-fold.
1. For `CAT.get_entities_multi_texts` and `CAT.multiprocessing_batch_docs_size` (which uses the former internally)
- Uses the `CAT.pipe` and `Pipe.batch_multi_processHad` directly
- Had to add logging to the input/output separately
2. For `CAT.multiprocessing_batch_char_size`
- Runs on different processes, which means that different instances are used
- And (for some reason) cleanup (i.e a `__del__` call - which would flush automatically) is not done
- Had to flush the usage monitor (i.e write to disk) at the end of each multiprocessing method (`CAT._mp_cons`) explicitly
The PR also adds tests to make sure the monitoring actually works as well. The 3 added tests failed in the previous state of the …
=> CU-8695pvhfe fix usage monitoring for multiprocessing

medcat/utils/normalizers.py, medcat/utils/regression/checking.py, medcat/utils/regression/regression_checker.py, medcat/utils/regression/targeting.py, medcat/utils/regression/utils.py, tests/utils/regression/test_utils.py, tests/utils/test_normalizers.py
Add option (`--edit-distance`) to specify name edit distance as a tuple (edit distance, random number generator seed, and number of picks).
We need to pick a subset of the edits since otherwise there can be thousands of edits checked - and that would slow down the process considerably.
And to avoid run-to-run variance we need to be able to specify a random seed for the picks.
<details>
<summary>Examples</summary>
Example without edit-distance:
```
$ python -m medcat.utils.regression.regression_checker models/20230227__kch_gstt_trained_model_494c3717f637bb89.zip --example-strictness None
Loading RegressionChecker from yaml: configs/default_regression_tests.yml
Loading model pack from file: models/20230227__kch_gstt_trained_model_494c3717f637bb89.zip
Checking the current status …
```
=> CU-8695knfbg Add name edits to regression suite

install_requires.txt
The latest version of `spacy` depends on `numpy>=2`. But we cannot support that due to other versions requiring `numpy<2`.
This incompatibility made the GHA workflow fail
So pinned `spacy` to less than 3.8 to fix this.
=> CU-869637yfx: Pin spacy dependency to lower than 3.8

.github/workflows/main.yml, setup.py
Python 3.8 is EoL since 7th of October. As such, it's time to stop support for it.
That is what this PR does. It:
- removes 3.8 from GitHub Actions workflow,
- removes 3.8 from classifiers,
- adds `python_requires='>=3.9'` to `setup.py` to disallow installation older python versions
- 3.8 is end of life
NOTE:
I considered adding a cap for newer python versions as well, but I didn't think it made sense in the large scheme of things since 3.12 support is held up behind `spacy` 3.12 support (which should be at `spacy==2.4.0`). It's not really under our control. It's also not currently possible to install `medcat` on these newer python versions anyway (due to no compatible `spacy`).
=> CU-86967nnra Drop python 3.8 support (EoL)

medcat/utils/preprocess_snomed.py, tests/utils/test_preprocess_snomed.py
Since #469 there's been a bit of an issue with preprocessing. Namely, it wasn't ignoring `UKClinicalRefsetsRF2` as it should have done.
I have made the necessary change.
The other small QoL change this PR introduces is the OPCS4 refset ID. Since end of 2023 the refset ID for OCS4 mappings is different. But the default had been the old ID. This PR reversed that logic and has the new refset ID as a default rather than the old one and changes to the old one if/when needed.
And the third thing that was problematic was checking of extension (e.g UK/UK Drug) outside the loop since extensions are now handled automatically and can change while iterating over them in a bundle.
To ensure this all works exactly as it should I ran a test on Snomed UK Clinical Edition and Drug Extension releases with …
=> CU-86964zm4d fix preprocessing

medcat/ner/transformers_ner.py
Refer to issue #501 
Apparently this snippet of code was (accidentally!) commented out when working towards #490 (in commit https://github.com/CogStack/MedCAT/pull/490/commits/5bb188d08b531a08adf9e06ea97c7c8a577043e8).
So this PR will fix that.
=> CU-8696n7w95: Remove commented code to fix DeID (oversight in PR 490)

medcat/utils/vocab_utils.py, tests/utils/test_vocab_utils.py
Adds a module to convert the vocab vectors from the default (or really anything) to a smaller length.
The default vocab vector length is 300. However, we don't really make use of all this information. Experiments show that we can go quite a lot smaller in vocab size and retain the same performance. See e.g: https://gist.github.com/mart-r/e9db909cde1922464bcc753f54006994
Or (somewhat more comprehensively): https://gist.github.com/mart-r/21460286466d17b9f23719ba3f4dc938
The benefits of using a smaller vocab size mainly boil down to (examples at 50 vector size):
- Smaller saved vocab on disk
- The vocab size can go from 314MB down to 142MB
- Or even to 68MB when ditching unigram table (see #503)
- The CDB size will also go down significantly
- Because the context vectors stored within it …
=> CU-8696nbm9j: Add module to convert vocab vectors

medcat/vocab.py, tests/test_vocab.py, tests/utils/saving/test_serialization.py
The unigram table we've been using is massive (10M-100M element array).
As such, when this gets saved to disk, it takes up a lot of space.
But really, all it is is a long array of numbers that are repeated based on the frequency they're expected (across all words).
E.g if you had words with equal counts, the number of their indices would be the same in the unigram table. And if you had some that had far higher counts, they would be far frequent in the unigram table.
What this PR does is remove the unigram table in favour of another approach.
This new approach finds the frequencies of all words, and then finds the cumulative probabilities (which is a sorted array starting near 0 and ending at 1 since we're adding up all the probabilities) for each word index.
And when it comes to getting …
=> CU-8696nbm03: Remove unigram table

medcat/stats/kfold.py, tests/stats/test_kfold.py
Currently, when splitting per-annotations, not all annotations are used.
In fact, only the annotations from the first few documents/projects would be used.
That is because for each fold, the number of annotations already used is not considered.
The PR adds a test to show that this is currently problematic (first commit).
And then introduces the relevant fix.
=> CU-8696v2j42: Add test to make sure per-cui counts are kept when creating folds

medcat/ner/transformers_ner.py, medcat/utils/relation_extraction/utils.py
Since `transformers==4.47.0` there's a different way they handle some of the tokenizer attributes (see https://github.com/huggingface/transformers/pull/34461). But our saved models have no idea of this change and keep the data in the old format. So when trying to run the DeID model, the new method is used to read the data, but there's nothing there to be read.
We haven't seen anyone really complain about this, but it's mostly due to the insallations being static. If someone installed before 17th of December, their installation would have `transformers<4.47` and unless they've updated since, their setup will still work just fine.
This PR fixes that. It moves the relevant data to the correct location upon creation of pipeline.
<details>
<summary>Verification that this fixes the …
=> CU-8697x7y9x: Fix issue with transformers 4.47+ affecting DeID

medcat/config_meta_cat.py, medcat/meta_cat.py, medcat/utils/meta_cat/data_utils.py, medcat/utils/meta_cat/ml_utils.py
- Addressing the multiple zero-division-error warnings per epoch while training
- Accommodating the variations in category name and class name across NHS sites; this is done by introducing 2 new config parameters: `category_names_map` and `class_names_map` that store the possible variations
=> Updates for MetaCAT

medcat/ner/transformers_ner.py, medcat/utils/ner/model.py, tests/ner/test_transformers_ner.py, tests/utils/ner/test_deid.py
This PR introduces methods that enable users to expand the transformers_ner model and its tokenizer by adding custom concepts for the downstream tasks, such as fine-tuning the DeID model.
=> Support expansion of transformers ner models to include new concepts

medcat/config_meta_cat.py, medcat/meta_cat.py, medcat/utils/meta_cat/data_utils.py
Fix some alternative name stuff:
- Separate the picking of appropriate category name
- Select category name correctly when using the `MetaCAT.eval` method
- Fix usage of `alternative_class_names` when encoding category names
- I.e use the correct class name rather than the list of the class name as a key in `category_value2id`
- Some other minor changes
- Lowering indentation
- Removing duplicate exceptions
=> CU-869805t7e alt names fixes

medcat/cat.py, tests/test_cat.py
This PR allows (optionally) training MetaCATs during supervised training.
It only trains MetaCATs for which the category name exists in the trainer export.
It also adds a few small tests to make sure this works correctly.
PS:
With #515 the check for suitable MetaCATs according to category name may need adjusting since the PR allows for alterantives category names.
=> CU-8697qfvzz train metacat on sup train

medcat/utils/meta_cat/ml_utils.py
In `transformers==4.50.0` the `AdamW` implementation was removed and the suggestion was to use the version in `torch.optim` instead:
https://github.com/huggingface/transformers/pull/36177
Before the change to the import (the first commit in thie branch / PR), the GHA workflow will fail due to this import not existing and our loose dependencies.
Though the change is rather simple - just change the import. And the 2nd commit workflow should be successful.
=> CU-8698ek477: Fix AdamW import from tranformers to torch

medcat/vocab.py, tests/test_vocab.py
MedCAT 1.15.0 (more specifically PR #503) removed the unigram table in favour of an approach that doesn't need the massive array that was used before.
However, during the implementation, some details were overlooked. Namely, the `Vocab` keeps track of two `dict`s. One for `index2word` and another for `vec_index2word`. The `index2word` map just maps the first `N` (the number of words in the vocab) postive integers to the corresponding word. The `vec_index2word` map does the same, however it omits words that don't have a corresponding vector. E.g it could have keys `[0, 1, 2, 4, 10, 15]`  - missing indices that don't have a corresponding word vector.
Now, when the cumulative frequencies are created, the original PR made the assumption that `vec_index2word` also maps all consecutive …
=> CU-8698f8fgc: Fix negative sampling including indices for words without a vector

medcat/cat.py
When saving a model, it's useful to add to the description the changes that were made that warranted the model save.
This PR adds an argument that does that.
It also dates the addition to the description with the save date.
=> CU-8698gkrqa: Add argument to allow specifying the changes warrenting a model save

medcat/ner/transformers_ner.py, medcat/utils/ner/deid.py, medcat/utils/ner/model.py, tests/test_transformers_ner.py
ignore_extra_labels doesn't ignore the extra labels without the `AutoModel` `from_pretrained` being passed the extra named arg
=> ignore_extra_labels on DeID Model Train / Eval

.github/workflows/production.yml
Similar to #533 - production workflow also needed this change.
PS:
Already made the change on the production branch.
=> CU-8698vj59x: Use Ubuntu 24.04 for production workflow

medcat/utils/helpers.py, medcat/utils/regression/checking.py
This small PR resolves the `logger.warn()` deprecation warnings:
```python
/home/runner/work/MedCAT/MedCAT/medcat/utils/regression/checking.py:455: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> Migrate to `logger.warning` usage

.readthedocs.yaml, pyproject.toml
ReadTheDocs builds are now failing.
Turns out that's because `pip==25.1` now removes the build process that's used on there (see [release notes](https://pip.pypa.io/en/stable/news/#:~:text=Deprecate%20the%20legacy%20setup.py%20bdist_wheel%20mechanism.%20To%20silence%20the%20warning%2C%20and%20future%2Dproof%20their%20setup%2C%20users%20should%20enable%20%2D%2Duse%2Dpep517%20or%20add%20a%20pyproject.toml%20file%20to%20the%20projects%20they%20control.%20(%2313319))).
So we are now forced to use a minimal `pyproject.toml`.
Though notably, we can get away with still using setup.py for most of the installation process.
So this PR will make that change.
The docs builds should work with this change alone. But I will - of course - make sure they do be enabling this branch as a version …
=> CU-8698x2k5b Fix read the docs builds

README.md
This PR notifies that v1.16 will be the latest minor relase of MedCAT v1 and adds a link to v2.
It also fixes a long-standing minor mistake with no-gpu torch installation in the docs.
=> CU-8698x5ehn Notification of final v1 version

medcat/utils/relation_extraction/bert/config.py, medcat/utils/relation_extraction/bert/model.py, medcat/utils/relation_extraction/llama/config.py, medcat/utils/relation_extraction/llama/model.py, medcat/utils/relation_extraction/llama/tokenizer.py, medcat/utils/relation_extraction/models.py, medcat/utils/relation_extraction/modernbert/config.py, medcat/utils/relation_extraction/modernbert/model.py
There were some typing issues that were resolved with this PR.
The gist of it has to do with specific models (i.e ModernBert or Llama) requiring model-specific configs isntead of the baseclass of `PretrainedConfig`.
Though the fix does need a `cast` operation, I moved all those jointly into `medcat.utils.relation_extraction.models`.
Though there's also casting of loaded config for each (Bert, ModernBert, Llama) due to the method signature of `.from_pretrained` and `.from_json_file` returning a `PretrainedConfig` rather than the specific one that it was called on. In reality, the calling class is returned anyway (since the implicit `cls` is initialised in both cases).
=> CU-86995mmb6 Fix some RelCAT typing issues
